###CREATE 
POST http://localhost:3000/historicals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAwMzg2MjZ9.el_ssoQ7RkmIUMs6i8tqhtxx0fOtGqH1oozUdlATIAA
Content-Type: application/json

###INDEX 
GET http://localhost:3000/historicals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAwMzg2MjZ9.el_ssoQ7RkmIUMs6i8tqhtxx0fOtGqH1oozUdlATIAA
Content-Type: application/json


###DELETE 
DELETE http://localhost:3000/historicals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAwMzg2MjZ9.el_ssoQ7RkmIUMs6i8tqhtxx0fOtGqH1oozUdlATIAA