###INDEX STOCKS####
GET http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Mzg2NDA1MzR9.h6rIBQdSOn0ytGzFDb0-wPiqHy493oe59kQ-KVEZGQU
Content-Type: application/json

###Show STOCK####
GET http://localhost:3000/stocks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc4NjYxMDN9.pHUFuTIjII_pf5YLovM44wTXmvH5mVQ3Rt9eg46vhaY
Content-Type: application/json

### CREATE STOCK###
POST http://localhost:3000/stocks/UUUU
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzkxNDY2OTR9.iLCfJRty6zmOH9oOHIPbEI-iHvZvQJ9ERc9ULO_J-0Y
Content-Type: application/json

{
  "quantity": 1,
  "cost_basis": 9
}

### UPDATE STOCK###
PATCH http://localhost:3000/stocks/CCJ.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzkxNDY2OTR9.iLCfJRty6zmOH9oOHIPbEI-iHvZvQJ9ERc9ULO_J-0Y
Content-Type: application/json

{
  "sector": "Uranium"
}

### Destroy STOCK###
DELETE http://localhost:3000/stocks/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzkxNDY2OTR9.iLCfJRty6zmOH9oOHIPbEI-iHvZvQJ9ERc9ULO_J-0Y
Content-Type: application/json