###INDEX STOCKS####
GET http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk4NDE3Nzh9.xF6KdUETSSf0ZF43DpF_BjBpdxb3txsEYagNfQBRekQ
Content-Type: application/json

###Show STOCK####
GET http://localhost:3000/stocks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc4NjYxMDN9.pHUFuTIjII_pf5YLovM44wTXmvH5mVQ3Rt9eg46vhaY
Content-Type: application/json

### CREATE STOCK###
POST http://localhost:3000/stocks/EPD
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk1ODMwMTl9.95UDFVZF21UjMEUJzw1-R-V58Y-GXOyTvRHqvo8nWQs
Content-Type: application/json

{
  "quantity": 10,
  "cost_basis": 16
}

### UPDATE STOCK###
PATCH http://localhost:3000/stocks/UUUU.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk3NjgyODF9.5BV3iGpQfMjNvWnHzUQLb2qCbzi404elmvch96YIn7c
Content-Type: application/json

{
  "cost_basis": 5
}

### Destroy STOCK###
DELETE http://localhost:3000/stocks/34
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk4NjE2Mzd9.DYfEq3NPCufz5mRzXDsqMMByAk60wVaC44q-ETavYuM
Content-Type: application/json