###INDEX STOCKS####
GET http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc0MzIzNjN9.J2ApoSOe87CcVSh6ra0i8p4qi3SKtDrkbu0CSBdSq5c
Content-Type: application/json

###Show STOCK####
GET http://localhost:3000/stocks/1
Content-Type: application/json

### CREATE STOCK###
POST http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc0Mzg2OTl9.ouiEWEvVptBq-PLJd4jcqxlJAqtYWn00t5k-aPMhdlo
Content-Type: application/json

{
  "symbol": "Fake",
  "company_name": "Fake Company",
  "cost_basis": 400,
  "current_price": 340.92,
  "quantity": 5
}
### UPDATE STOCK###
PUT http://localhost:3000/stocks/9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc1OTgxNzJ9.K4emx8x4HZdLbYOcbKDSXO28eUzJx2sBS-LnjxqYyGg
Content-Type: application/json

{
  "sector_id": 3,
  "industry_id": 4
}

### Destroy STOCK###
DELETE http://localhost:3000/stocks/5
Authorization: Bearer
Content-Type: application/json