GET http://localhost:3000/sectors.json
Content-Type: application/json

###CREATE SECTOR
POST http://localhost:3000/sectors.json
Content-Type: application/json

{
  "sector": "Fake Sector"
}

### DELETE SECTOR
DELETE http://localhost:3000/sectors/38.json