###INDEX STOCKS####
GET http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAyOTUwODB9.1vejGoIRTleeHL2K4zuQ3Q4RATy7BfQFXAwWoYqwdmo
Content-Type: application/json

###Show STOCK####
GET http://localhost:3000/stocks/92
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAyOTU1NzF9.RQH69G2vxnbjyzV_AabncBOmPcvi7rVJSgGCJVPBesw
Content-Type: application/json

### CREATE STOCK###
POST http://localhost:3000/stocks/ENB
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDAyOTU4NzJ9.LPsToGNiN3SVcpa2SHpXMTUwjKnT6AM79OsRYXJV14A
Content-Type: application/json

{
  "quantity": 10,
  "cost_basis": 15
}

### UPDATE STOCK###
PATCH http://localhost:3000/stocks/UUUU.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk3NjgyODF9.5BV3iGpQfMjNvWnHzUQLb2qCbzi404elmvch96YIn7c
Content-Type: application/json

{
  "cost_basis": 5
}

### Destroy STOCK###
DELETE http://localhost:3000/stocks/88
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDAyOTU1NzF9.RQH69G2vxnbjyzV_AabncBOmPcvi7rVJSgGCJVPBesw
Content-Type: application/json