### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test",
  "email": "test1@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Users destroy (signup)
DELETE http://localhost:3000/users/4
Content-Type: application/json
